### ISSUE TITLE
Hard-wiring into the CXA

### ISSUE THREAD

**Issue by levid0s** [ozfive/CXA81-IR-Remote-Server#2]
Noob question, but instead of using an IR transmitter and an IR receiver, can I just send the electrical signal from the GPIO pins into the CXA's 3.5mm Remote In port?

Thanks

**Comment by levid0s** [comment]
Can confirm that hardwiring directly into the CXA81's IR In port, using the 3.5mm mono jack, works. No need to convert to signal to IR light and back.

I added a 220 Ohm resistor on the line to protect for eventual high current.

Thanks a lot for the project ozfive.

**Comment by jnyadams** [comment]
Hi livid0s,

Appreciate this is a couple of years old now - was wondering if you'd be able to share with me how you wired this?

Thanks

**Comment by levid0s** [comment]
Hello,

I wired it straight from the GPIO IR ports to the CXA IR port. I added a 100 ohm resistor on the red cable just for safety. (I think polarity doesn't matter). 

Since my last comment I've been actively using this, works beautifully. 

![image](https://github.com/user-attachments/assets/49d3ccab-29e5-47a9-b6ea-118da4b59049)

![image](https://github.com/user-attachments/assets/afdba6e8-e22b-41f8-9950-7e07e87d99e2)

![image](https://github.com/user-attachments/assets/9ef56e6b-ee5e-470d-a980-2827e4f21e89)
